# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_stages: [commit, manual]

repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.3
      hooks:
        - id: ruff
          name: "ruff on kedro/, tests/ and docs/"
          args: ["--fix", "--exit-non-zero-on-fix"]
          exclude: "^kedro/templates/|^features/steps/test_starter/"
        - id: ruff-format
          name: "ruff format on kedro/, features/ and tests/"
          files: "^kedro/|^features/|^tests/"
          exclude: "^features/steps/test_starter|^kedro/templates/"

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.3
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml # Checks yaml files for parseable syntax.
            exclude: "^kedro/templates/|^features/steps/test_starter/"
          - id: check-json # Checks json files for parseable syntax.
          - id: check-added-large-files
          - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
          - id: check-merge-conflict # Check for files that contain merge conflict strings.
          - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
            exclude: "^kedro/templates/|^features/steps/test_starter/"
          - id: requirements-txt-fixer # Sorts entries in requirements.txt
            exclude: "^kedro/templates/|^features/steps/test_starter/"

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.961
      hooks:
          - id: mypy
            args: [--allow-redefinition, --ignore-missing-imports]
            exclude: |
                (?x)(
                  ^kedro/templates/|
                  ^docs/|
                  ^features/steps/test_starter/
                )
            additional_dependencies:
            - types-cachetools
            - types-filelock
            - types-PyYAML
            - types-redis
            - types-requests
            - types-setuptools
            - types-toml
            - attrs

    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
          - id: blacken-docs
            additional_dependencies:
            - black~=23.0
            entry: blacken-docs --skip-errors

    - repo: local
      hooks:
          - id: imports
            name: "Import Linter"
            language: system
            pass_filenames: false
            entry: lint-imports

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.961
      hooks:
          - id: mypy
            args: [--allow-redefinition, --ignore-missing-imports]
            exclude: |
                (?x)(
                  ^kedro/templates/|
                  ^docs/|
                  ^features/steps/test_starter/
                )
            additional_dependencies:
            - types-cachetools
            - types-filelock
            - types-PyYAML
            - types-redis
            - types-requests
            - types-setuptools
            - types-toml
            - attrs
    - repo: local
      hooks:
          # Slow lintint
          - id: secret_scan
            name: "Secret scan"
            language: system
            exclude: ^features/steps/test_starter
            pass_filenames: false
            entry: make secret-scan
          - id: bandit
            name: "Bandit security check"
            language: system
            types: [file, python]
            exclude: ^kedro/templates/|^tests/|^features/steps/test_starter
            entry: bandit -ll

# Manual only
