# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_stages: [pre-commit, manual]

repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.7.1
      hooks:
        - id: ruff
          name: "ruff on kedro/, tests/ and docs/"
          args: ["--fix", "--exit-non-zero-on-fix"]
          exclude: "^kedro/templates/|^features/steps/test_starter/"
        - id: ruff-format
          name: "ruff format on kedro/, features/ and tests/"
          files: "^kedro/|^features/|^tests/"
          exclude: "^features/steps/test_starter|^kedro/templates/"

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml # Checks yaml files for parseable syntax.
            exclude: "^kedro/templates/|^features/steps/test_starter/"
          - id: check-json # Checks json files for parseable syntax.
          - id: check-added-large-files
          - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
          - id: check-merge-conflict # Check for files that contain merge conflict strings.
          - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
            exclude: "^kedro/templates/|^features/steps/test_starter/"
          - id: requirements-txt-fixer # Sorts entries in requirements.txt
            exclude: "^kedro/templates/|^features/steps/test_starter/"

    - repo: local
      hooks:
          - id: imports
            name: "Import Linter"
            language: system
            pass_filenames: false
            entry: lint-imports

    - repo: local
      hooks:
          - id: secret_scan
            name: "Secret scan"
            language: system
            exclude: ^features/steps/test_starter
            pass_filenames: false
            entry: make secret-scan
