name: Run nightly tests on Kedro

on:
  workflow_dispatch:
  schedule:
    # Run every day at midnight (UTC time)
    - cron: '0 0 * * *'

jobs:
  kedro-test:
    strategy:
      matrix:
        branch: [ main, develop ]
    uses: ./.github/workflows/all-checks.yml
    with:
      branch: ${{ matrix.branch }}

  notify-kedro:
    permissions:
      issues: write
    name: Notify failed build for kedro
    needs: kedro-test
    if: ${{ !success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: jayqi/failed-build-issue-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-name: "nightly build"
          title-template: "ci: Nightly build failure"
          body-template: |
            GitHub Actions workflow [{{workflow}} #{{runNumber}}](https://github.com/{{repo.owner}}/{{repo.repo}}/actions/runs/{{runId}}) failed.
          create-label: true
          always-create-new-issue: false
